/**
 * Incident Report Export
 * 
 * Generate markdown reports for tasks
 */

import { v } from "convex/values";
import { query } from "./_generated/server";

export const generateIncidentReport = query({
  args: { taskId: v.id("tasks") },
  handler: async (ctx, args) => {
    const task = await ctx.db.get(args.taskId);
    if (!task) {
      throw new Error("Task not found");
    }
    
    const transitions = await ctx.db
      .query("taskTransitions")
      .withIndex("by_task", (q) => q.eq("taskId", args.taskId))
      .collect();
    
    const messages = await ctx.db
      .query("messages")
      .withIndex("by_task", (q) => q.eq("taskId", args.taskId))
      .collect();
    
    const approvals = await ctx.db
      .query("approvals")
      .withIndex("by_task", (q) => q.eq("taskId", args.taskId))
      .collect();
    
    const runs = await ctx.db
      .query("runs")
      .withIndex("by_task", (q) => q.eq("taskId", args.taskId))
      .collect();
    
    // Calculate costs
    const totalCost = runs.reduce((sum, r) => sum + (r.costUsd || 0), 0);
    
    // Generate markdown
    let report = `# Incident Report: ${task.title}\n\n`;
    report += `**Task ID:** ${task._id}\n`;
    report += `**Status:** ${task.status}\n`;
    report += `**Type:** ${task.type}\n`;
    report += `**Priority:** ${task.priority}\n`;
    report += `**Created:** ${new Date(task._creationTime).toISOString()}\n`;
    report += `**Total Cost:** $${totalCost.toFixed(2)}\n\n`;
    
    if (task.description) {
      report += `## Description\n\n${task.description}\n\n`;
    }
    
    report += `## Timeline\n\n`;
    for (const t of transitions) {
      report += `- ${new Date(t._creationTime).toISOString()} - ${t.fromStatus} → ${t.toStatus}\n`;
      if (t.reason) report += `  *${t.reason}*\n`;
    }
    
    report += `\n## Messages (${messages.length})\n\n`;
    for (const m of messages.slice(0, 10)) {
      report += `### ${new Date(m._creationTime).toISOString()}\n`;
      report += `**Type:** ${m.type}\n`;
      report += `${m.content}\n\n`;
    }
    
    if (messages.length > 10) {
      report += `*... and ${messages.length - 10} more messages*\n\n`;
    }
    
    report += `\n## Approvals (${approvals.length})\n\n`;
    for (const a of approvals) {
      report += `- **${a.actionSummary}** - ${a.status}\n`;
      report += `  Risk: ${a.riskLevel}, Cost: $${a.estimatedCost?.toFixed(2) || 0}\n`;
      if (a.justification) {
        report += `  Justification: ${a.justification}\n`;
      }
    }
    
    report += `\n## Execution Runs (${runs.length})\n\n`;
    for (const r of runs) {
      report += `- ${r.status} - Cost: $${r.costUsd?.toFixed(2) || 0}\n`;
      if (r.error) {
        report += `  Error: ${r.error}\n`;
      }
    }
    
    report += `\n---\n\n`;
    report += `*Generated by Mission Control on ${new Date().toISOString()}*\n`;
    
    return { report, task, totalCost };
  },
});
