/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as activities from "../activities.js";
import type * as agentDocuments from "../agentDocuments.js";
import type * as agentHiring from "../agentHiring.js";
import type * as agentLearning from "../agentLearning.js";
import type * as agents from "../agents.js";
import type * as alertRules from "../alertRules.js";
import type * as alerts from "../alerts.js";
import type * as analytics from "../analytics.js";
import type * as apiCollections from "../apiCollections.js";
import type * as approvals from "../approvals.js";
import type * as automationExecutions from "../automationExecutions.js";
import type * as automationScheduler from "../automationScheduler.js";
import type * as automations from "../automations.js";
import type * as captures from "../captures.js";
import type * as codegen from "../codegen.js";
import type * as comments from "../comments.js";
import type * as companyContext from "../companyContext.js";
import type * as companyMembers from "../companyMembers.js";
import type * as contentDrops from "../contentDrops.js";
import type * as context_activation from "../context/activation.js";
import type * as context_analyzeGithubRepo from "../context/analyzeGithubRepo.js";
import type * as context_changeRisk from "../context/changeRisk.js";
import type * as context_evals from "../context/evals.js";
import type * as context_importSkills from "../context/importSkills.js";
import type * as context_manifests from "../context/manifests.js";
import type * as context_packageFiles from "../context/packageFiles.js";
import type * as context_packages from "../context/packages.js";
import type * as context_verifiers from "../context/verifiers.js";
import type * as coordinator from "../coordinator.js";
import type * as costEvents from "../costEvents.js";
import type * as crons from "../crons.js";
import type * as e2e from "../e2e.js";
import type * as eos_projections from "../eos/projections.js";
import type * as evalControlPlane from "../evalControlPlane.js";
import type * as execution from "../execution.js";
import type * as executionRequests from "../executionRequests.js";
import type * as executionRouting from "../executionRouting.js";
import type * as executionWorker from "../executionWorker.js";
import type * as executorRouter from "../executorRouter.js";
import type * as executors from "../executors.js";
import type * as factory_agentFleet from "../factory/agentFleet.js";
import type * as factory_attempts from "../factory/attempts.js";
import type * as factory_automationDefinitions from "../factory/automationDefinitions.js";
import type * as factory_automationDispatch from "../factory/automationDispatch.js";
import type * as factory_codeReviewWizard from "../factory/codeReviewWizard.js";
import type * as factory_configuration from "../factory/configuration.js";
import type * as factory_executionProfiles from "../factory/executionProfiles.js";
import type * as factory_githubCi from "../factory/githubCi.js";
import type * as factory_governedMcp from "../factory/governedMcp.js";
import type * as factory_health from "../factory/health.js";
import type * as factory_learning from "../factory/learning.js";
import type * as factory_metaLoop from "../factory/metaLoop.js";
import type * as factory_piBridge from "../factory/piBridge.js";
import type * as factory_prChecks from "../factory/prChecks.js";
import type * as factory_providerLiability from "../factory/providerLiability.js";
import type * as factory_releases from "../factory/releases.js";
import type * as factory_repetitiveTasks from "../factory/repetitiveTasks.js";
import type * as factory_workflows from "../factory/workflows.js";
import type * as factoryMemory from "../factoryMemory.js";
import type * as featureFlags from "../featureFlags.js";
import type * as flakySteps from "../flakySteps.js";
import type * as gatewayConnection from "../gatewayConnection.js";
import type * as gherkin from "../gherkin.js";
import type * as github from "../github.js";
import type * as githubAppConnections from "../githubAppConnections.js";
import type * as goals from "../goals.js";
import type * as governance_approvalRecords from "../governance/approvalRecords.js";
import type * as governance_changeRecords from "../governance/changeRecords.js";
import type * as governance_deployments from "../governance/deployments.js";
import type * as governance_permissions from "../governance/permissions.js";
import type * as governance_policyEnvelopes from "../governance/policyEnvelopes.js";
import type * as governance_releaseGateAutomation from "../governance/releaseGateAutomation.js";
import type * as governance_roleAssignments from "../governance/roleAssignments.js";
import type * as governance_roles from "../governance/roles.js";
import type * as governancePolicies from "../governancePolicies.js";
import type * as health from "../health.js";
import type * as http from "../http.js";
import type * as hybridWorkflows from "../hybridWorkflows.js";
import type * as identity from "../identity.js";
import type * as inferenceGateway from "../inferenceGateway.js";
import type * as knowledge from "../knowledge.js";
import type * as knowledgeGraph from "../knowledgeGraph.js";
import type * as lib_agentResolver from "../lib/agentResolver.js";
import type * as lib_armAudit from "../lib/armAudit.js";
import type * as lib_armCompat from "../lib/armCompat.js";
import type * as lib_armPolicy from "../lib/armPolicy.js";
import type * as lib_authorizationRollout from "../lib/authorizationRollout.js";
import type * as lib_automationDispatch from "../lib/automationDispatch.js";
import type * as lib_automationGovernance from "../lib/automationGovernance.js";
import type * as lib_bedrockBridgeIdentity from "../lib/bedrockBridgeIdentity.js";
import type * as lib_companyAccess from "../lib/companyAccess.js";
import type * as lib_companyContextGate from "../lib/companyContextGate.js";
import type * as lib_companyMemberPolicy from "../lib/companyMemberPolicy.js";
import type * as lib_contextActivation from "../lib/contextActivation.js";
import type * as lib_contextEvals from "../lib/contextEvals.js";
import type * as lib_contextManifests from "../lib/contextManifests.js";
import type * as lib_contextPackages from "../lib/contextPackages.js";
import type * as lib_contextRegistryGate from "../lib/contextRegistryGate.js";
import type * as lib_continuousResearchEvidence from "../lib/continuousResearchEvidence.js";
import type * as lib_continuousResearchProjection from "../lib/continuousResearchProjection.js";
import type * as lib_currentVerification from "../lib/currentVerification.js";
import type * as lib_deliveryAuthorization from "../lib/deliveryAuthorization.js";
import type * as lib_demoSeedExtensions from "../lib/demoSeedExtensions.js";
import type * as lib_dockerAllocationRecovery from "../lib/dockerAllocationRecovery.js";
import type * as lib_dockerSandboxAdmission from "../lib/dockerSandboxAdmission.js";
import type * as lib_evalControlPlaneSchema from "../lib/evalControlPlaneSchema.js";
import type * as lib_evalFrameworkGate from "../lib/evalFrameworkGate.js";
import type * as lib_evidenceAuthority from "../lib/evidenceAuthority.js";
import type * as lib_executionManifest from "../lib/executionManifest.js";
import type * as lib_executionPolicy from "../lib/executionPolicy.js";
import type * as lib_executionProfile from "../lib/executionProfile.js";
import type * as lib_executionProfileAdmission from "../lib/executionProfileAdmission.js";
import type * as lib_executionRecovery from "../lib/executionRecovery.js";
import type * as lib_executionRouting from "../lib/executionRouting.js";
import type * as lib_factoryActionAuthorization from "../lib/factoryActionAuthorization.js";
import type * as lib_factoryAttempt from "../lib/factoryAttempt.js";
import type * as lib_factoryConfiguration from "../lib/factoryConfiguration.js";
import type * as lib_factoryDispatch from "../lib/factoryDispatch.js";
import type * as lib_factoryHealth from "../lib/factoryHealth.js";
import type * as lib_factoryHumanReview from "../lib/factoryHumanReview.js";
import type * as lib_factoryLearning from "../lib/factoryLearning.js";
import type * as lib_factoryMemory from "../lib/factoryMemory.js";
import type * as lib_factoryMemoryDemoSeed from "../lib/factoryMemoryDemoSeed.js";
import type * as lib_factoryMemoryGate from "../lib/factoryMemoryGate.js";
import type * as lib_factoryMemoryTelemetry from "../lib/factoryMemoryTelemetry.js";
import type * as lib_factoryMemoryValidators from "../lib/factoryMemoryValidators.js";
import type * as lib_factoryModelRoute from "../lib/factoryModelRoute.js";
import type * as lib_factoryOverview from "../lib/factoryOverview.js";
import type * as lib_factoryProjectSeed from "../lib/factoryProjectSeed.js";
import type * as lib_factoryRelease from "../lib/factoryRelease.js";
import type * as lib_factoryReviewReadModel from "../lib/factoryReviewReadModel.js";
import type * as lib_factoryWorkerRuntime from "../lib/factoryWorkerRuntime.js";
import type * as lib_factoryWorkflowContract from "../lib/factoryWorkflowContract.js";
import type * as lib_fileTree from "../lib/fileTree.js";
import type * as lib_flags from "../lib/flags.js";
import type * as lib_genomeHash from "../lib/genomeHash.js";
import type * as lib_getActiveTenant from "../lib/getActiveTenant.js";
import type * as lib_githubAppAuth from "../lib/githubAppAuth.js";
import type * as lib_githubAppReadiness from "../lib/githubAppReadiness.js";
import type * as lib_githubCiIngest from "../lib/githubCiIngest.js";
import type * as lib_githubRepoSkills from "../lib/githubRepoSkills.js";
import type * as lib_governedInferenceAdmission from "../lib/governedInferenceAdmission.js";
import type * as lib_governedMcp from "../lib/governedMcp.js";
import type * as lib_graphEngineering from "../lib/graphEngineering.js";
import type * as lib_harnessCapabilities from "../lib/harnessCapabilities.js";
import type * as lib_harnessPrChecks from "../lib/harnessPrChecks.js";
import type * as lib_knowledgeGraph from "../lib/knowledgeGraph.js";
import type * as lib_legacyToolPolicy from "../lib/legacyToolPolicy.js";
import type * as lib_localCandidateRecovery from "../lib/localCandidateRecovery.js";
import type * as lib_loopEngineering from "../lib/loopEngineering.js";
import type * as lib_loopResearchEvidence from "../lib/loopResearchEvidence.js";
import type * as lib_loopWorkflowProjection from "../lib/loopWorkflowProjection.js";
import type * as lib_mergeGates from "../lib/mergeGates.js";
import type * as lib_metaLoopSignals from "../lib/metaLoopSignals.js";
import type * as lib_missionDraft from "../lib/missionDraft.js";
import type * as lib_missionExecution from "../lib/missionExecution.js";
import type * as lib_missionGovernance from "../lib/missionGovernance.js";
import type * as lib_missionIntentContributionValidators from "../lib/missionIntentContributionValidators.js";
import type * as lib_missionIntentContributions from "../lib/missionIntentContributions.js";
import type * as lib_missionPlan from "../lib/missionPlan.js";
import type * as lib_missionPlanningRunState from "../lib/missionPlanningRunState.js";
import type * as lib_missionPromptScheduling from "../lib/missionPromptScheduling.js";
import type * as lib_missionSpec from "../lib/missionSpec.js";
import type * as lib_missionSpecDemo from "../lib/missionSpecDemo.js";
import type * as lib_missionSpecValidators from "../lib/missionSpecValidators.js";
import type * as lib_missionWorkOrderContract from "../lib/missionWorkOrderContract.js";
import type * as lib_modelCatalogScope from "../lib/modelCatalogScope.js";
import type * as lib_modelRouteAdmission from "../lib/modelRouteAdmission.js";
import type * as lib_modelRouting from "../lib/modelRouting.js";
import type * as lib_observability from "../lib/observability.js";
import type * as lib_observabilityPersistence from "../lib/observabilityPersistence.js";
import type * as lib_operatorControls from "../lib/operatorControls.js";
import type * as lib_operatorEvals from "../lib/operatorEvals.js";
import type * as lib_outputValidation from "../lib/outputValidation.js";
import type * as lib_piBridgeEnvelope from "../lib/piBridgeEnvelope.js";
import type * as lib_pilotLiabilityAllocation from "../lib/pilotLiabilityAllocation.js";
import type * as lib_policyV2Verification from "../lib/policyV2Verification.js";
import type * as lib_prEvaluation from "../lib/prEvaluation.js";
import type * as lib_prdParser from "../lib/prdParser.js";
import type * as lib_preExecutionRecovery from "../lib/preExecutionRecovery.js";
import type * as lib_providerLiability from "../lib/providerLiability.js";
import type * as lib_providerLiabilityValidators from "../lib/providerLiabilityValidators.js";
import type * as lib_qualityContract from "../lib/qualityContract.js";
import type * as lib_qualityGateDecision from "../lib/qualityGateDecision.js";
import type * as lib_rateLimit from "../lib/rateLimit.js";
import type * as lib_readOnlyRunControl from "../lib/readOnlyRunControl.js";
import type * as lib_repetitiveTaskCandidates from "../lib/repetitiveTaskCandidates.js";
import type * as lib_repetitiveTasks from "../lib/repetitiveTasks.js";
import type * as lib_repositoryExecutionPolicy from "../lib/repositoryExecutionPolicy.js";
import type * as lib_researchEvidenceBundle from "../lib/researchEvidenceBundle.js";
import type * as lib_researchIngestionPolicy from "../lib/researchIngestionPolicy.js";
import type * as lib_researchSourcePolicy from "../lib/researchSourcePolicy.js";
import type * as lib_reviewIntelligence from "../lib/reviewIntelligence.js";
import type * as lib_reviewIntelligenceValidators from "../lib/reviewIntelligenceValidators.js";
import type * as lib_reviewPackage from "../lib/reviewPackage.js";
import type * as lib_riskClassifier from "../lib/riskClassifier.js";
import type * as lib_runInspector from "../lib/runInspector.js";
import type * as lib_runtimeContract from "../lib/runtimeContract.js";
import type * as lib_sandboxProfileAdmission from "../lib/sandboxProfileAdmission.js";
import type * as lib_sanitize from "../lib/sanitize.js";
import type * as lib_serviceCommandAuth from "../lib/serviceCommandAuth.js";
import type * as lib_skillAutomation from "../lib/skillAutomation.js";
import type * as lib_softwareFactoryControlPlane from "../lib/softwareFactoryControlPlane.js";
import type * as lib_stateMachine from "../lib/stateMachine.js";
import type * as lib_taskAttemptScheduler from "../lib/taskAttemptScheduler.js";
import type * as lib_taskAuthority from "../lib/taskAuthority.js";
import type * as lib_taskEvents from "../lib/taskEvents.js";
import type * as lib_taskProjection from "../lib/taskProjection.js";
import type * as lib_taskWorkflowState from "../lib/taskWorkflowState.js";
import type * as lib_verificationPersistence from "../lib/verificationPersistence.js";
import type * as lib_workOrderCompat from "../lib/workOrderCompat.js";
import type * as lib_workOrderCreate from "../lib/workOrderCreate.js";
import type * as lib_workOrderDispatch from "../lib/workOrderDispatch.js";
import type * as lib_workOrderGovernance from "../lib/workOrderGovernance.js";
import type * as lib_workOrderParentSync from "../lib/workOrderParentSync.js";
import type * as lib_workOrderReadiness from "../lib/workOrderReadiness.js";
import type * as lib_workOrderRevision from "../lib/workOrderRevision.js";
import type * as lib_workOrderSpecification from "../lib/workOrderSpecification.js";
import type * as lib_workOrderSpecificationValidators from "../lib/workOrderSpecificationValidators.js";
import type * as lib_workOrders from "../lib/workOrders.js";
import type * as lib_workflowExecutionControl from "../lib/workflowExecutionControl.js";
import type * as lib_workflowObservability from "../lib/workflowObservability.js";
import type * as lib_workflowRunState from "../lib/workflowRunState.js";
import type * as lib_workflowSnapshot from "../lib/workflowSnapshot.js";
import type * as lib_workflowTaskGuards from "../lib/workflowTaskGuards.js";
import type * as lib_workspaceBindings from "../lib/workspaceBindings.js";
import type * as lib_workspaceRepositories from "../lib/workspaceRepositories.js";
import type * as loopEngineering from "../loopEngineering.js";
import type * as loops from "../loops.js";
import type * as meetings from "../meetings.js";
import type * as memoryLifecycle from "../memoryLifecycle.js";
import type * as messages from "../messages.js";
import type * as metrics from "../metrics.js";
import type * as migrations_backfillInstanceRefs from "../migrations/backfillInstanceRefs.js";
import type * as mission from "../mission.js";
import type * as missionChat from "../missionChat.js";
import type * as missionIntentContributions from "../missionIntentContributions.js";
import type * as missionPlanning from "../missionPlanning.js";
import type * as missionSpecs from "../missionSpecs.js";
import type * as missions from "../missions.js";
import type * as modelCatalog from "../modelCatalog.js";
import type * as modelRoutingDecisions from "../modelRoutingDecisions.js";
import type * as modelRoutingPolicies from "../modelRoutingPolicies.js";
import type * as monitoring from "../monitoring.js";
import type * as notifications from "../notifications.js";
import type * as observability from "../observability.js";
import type * as openclawDiscovery from "../openclawDiscovery.js";
import type * as operations_opEvents from "../operations/opEvents.js";
import type * as operatorControls from "../operatorControls.js";
import type * as operatorEvals from "../operatorEvals.js";
import type * as orgAssignments from "../orgAssignments.js";
import type * as orgMembers from "../orgMembers.js";
import type * as phaseZeroCanary from "../phaseZeroCanary.js";
import type * as planning from "../planning.js";
import type * as policy from "../policy.js";
import type * as prd from "../prd.js";
import type * as projects from "../projects.js";
import type * as qcArtifacts from "../qcArtifacts.js";
import type * as qcFindings from "../qcFindings.js";
import type * as qcMetrics from "../qcMetrics.js";
import type * as qcRulesets from "../qcRulesets.js";
import type * as qcRuns from "../qcRuns.js";
import type * as quotaTracking from "../quotaTracking.js";
import type * as registry_agentIdentities from "../registry/agentIdentities.js";
import type * as registry_agentInstances from "../registry/agentInstances.js";
import type * as registry_agentTemplates from "../registry/agentTemplates.js";
import type * as registry_agentVersions from "../registry/agentVersions.js";
import type * as registry_environments from "../registry/environments.js";
import type * as registry_operators from "../registry/operators.js";
import type * as registry_tenants from "../registry/tenants.js";
import type * as reports from "../reports.js";
import type * as researchIngestion from "../researchIngestion.js";
import type * as researchIngestionActions from "../researchIngestionActions.js";
import type * as researchSources from "../researchSources.js";
import type * as revenue from "../revenue.js";
import type * as reviewIntelligence from "../reviewIntelligence.js";
import type * as reviews from "../reviews.js";
import type * as runs from "../runs.js";
import type * as runtimeCompatibility from "../runtimeCompatibility.js";
import type * as savedViews from "../savedViews.js";
import type * as scheduledJobs from "../scheduledJobs.js";
import type * as search from "../search.js";
import type * as seed from "../seed.js";
import type * as seedAgentHiring from "../seedAgentHiring.js";
import type * as seedMemory from "../seedMemory.js";
import type * as seedMissionControlDemo from "../seedMissionControlDemo.js";
import type * as seedOrgChart from "../seedOrgChart.js";
import type * as seedSellerFi from "../seedSellerFi.js";
import type * as serviceCommands from "../serviceCommands.js";
import type * as sessionBootstrap from "../sessionBootstrap.js";
import type * as setupProjects from "../setupProjects.js";
import type * as setupSellerFiAgents from "../setupSellerFiAgents.js";
import type * as skillAutomations from "../skillAutomations.js";
import type * as softwareFactoryControlPlane from "../softwareFactoryControlPlane.js";
import type * as squad from "../squad.js";
import type * as standup from "../standup.js";
import type * as subscriptions from "../subscriptions.js";
import type * as taskRelations from "../taskRelations.js";
import type * as taskRouter from "../taskRouter.js";
import type * as tasks from "../tasks.js";
import type * as telegram from "../telegram.js";
import type * as telegraph from "../telegraph.js";
import type * as testGeneration from "../testGeneration.js";
import type * as testRecordings from "../testRecordings.js";
import type * as threadManager from "../threadManager.js";
import type * as transitions from "../transitions.js";
import type * as voice from "../voice.js";
import type * as watchSubscriptions from "../watchSubscriptions.js";
import type * as webhooks from "../webhooks.js";
import type * as workOrders from "../workOrders.js";
import type * as workflowMetrics from "../workflowMetrics.js";
import type * as workflowRecoveryCanary from "../workflowRecoveryCanary.js";
import type * as workflowRuns from "../workflowRuns.js";
import type * as workflows from "../workflows.js";
import type * as workspaceHostBindings from "../workspaceHostBindings.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  activities: typeof activities;
  agentDocuments: typeof agentDocuments;
  agentHiring: typeof agentHiring;
  agentLearning: typeof agentLearning;
  agents: typeof agents;
  alertRules: typeof alertRules;
  alerts: typeof alerts;
  analytics: typeof analytics;
  apiCollections: typeof apiCollections;
  approvals: typeof approvals;
  automationExecutions: typeof automationExecutions;
  automationScheduler: typeof automationScheduler;
  automations: typeof automations;
  captures: typeof captures;
  codegen: typeof codegen;
  comments: typeof comments;
  companyContext: typeof companyContext;
  companyMembers: typeof companyMembers;
  contentDrops: typeof contentDrops;
  "context/activation": typeof context_activation;
  "context/analyzeGithubRepo": typeof context_analyzeGithubRepo;
  "context/changeRisk": typeof context_changeRisk;
  "context/evals": typeof context_evals;
  "context/importSkills": typeof context_importSkills;
  "context/manifests": typeof context_manifests;
  "context/packageFiles": typeof context_packageFiles;
  "context/packages": typeof context_packages;
  "context/verifiers": typeof context_verifiers;
  coordinator: typeof coordinator;
  costEvents: typeof costEvents;
  crons: typeof crons;
  e2e: typeof e2e;
  "eos/projections": typeof eos_projections;
  evalControlPlane: typeof evalControlPlane;
  execution: typeof execution;
  executionRequests: typeof executionRequests;
  executionRouting: typeof executionRouting;
  executionWorker: typeof executionWorker;
  executorRouter: typeof executorRouter;
  executors: typeof executors;
  "factory/agentFleet": typeof factory_agentFleet;
  "factory/attempts": typeof factory_attempts;
  "factory/automationDefinitions": typeof factory_automationDefinitions;
  "factory/automationDispatch": typeof factory_automationDispatch;
  "factory/codeReviewWizard": typeof factory_codeReviewWizard;
  "factory/configuration": typeof factory_configuration;
  "factory/executionProfiles": typeof factory_executionProfiles;
  "factory/githubCi": typeof factory_githubCi;
  "factory/governedMcp": typeof factory_governedMcp;
  "factory/health": typeof factory_health;
  "factory/learning": typeof factory_learning;
  "factory/metaLoop": typeof factory_metaLoop;
  "factory/piBridge": typeof factory_piBridge;
  "factory/prChecks": typeof factory_prChecks;
  "factory/providerLiability": typeof factory_providerLiability;
  "factory/releases": typeof factory_releases;
  "factory/repetitiveTasks": typeof factory_repetitiveTasks;
  "factory/workflows": typeof factory_workflows;
  factoryMemory: typeof factoryMemory;
  featureFlags: typeof featureFlags;
  flakySteps: typeof flakySteps;
  gatewayConnection: typeof gatewayConnection;
  gherkin: typeof gherkin;
  github: typeof github;
  githubAppConnections: typeof githubAppConnections;
  goals: typeof goals;
  "governance/approvalRecords": typeof governance_approvalRecords;
  "governance/changeRecords": typeof governance_changeRecords;
  "governance/deployments": typeof governance_deployments;
  "governance/permissions": typeof governance_permissions;
  "governance/policyEnvelopes": typeof governance_policyEnvelopes;
  "governance/releaseGateAutomation": typeof governance_releaseGateAutomation;
  "governance/roleAssignments": typeof governance_roleAssignments;
  "governance/roles": typeof governance_roles;
  governancePolicies: typeof governancePolicies;
  health: typeof health;
  http: typeof http;
  hybridWorkflows: typeof hybridWorkflows;
  identity: typeof identity;
  inferenceGateway: typeof inferenceGateway;
  knowledge: typeof knowledge;
  knowledgeGraph: typeof knowledgeGraph;
  "lib/agentResolver": typeof lib_agentResolver;
  "lib/armAudit": typeof lib_armAudit;
  "lib/armCompat": typeof lib_armCompat;
  "lib/armPolicy": typeof lib_armPolicy;
  "lib/authorizationRollout": typeof lib_authorizationRollout;
  "lib/automationDispatch": typeof lib_automationDispatch;
  "lib/automationGovernance": typeof lib_automationGovernance;
  "lib/bedrockBridgeIdentity": typeof lib_bedrockBridgeIdentity;
  "lib/companyAccess": typeof lib_companyAccess;
  "lib/companyContextGate": typeof lib_companyContextGate;
  "lib/companyMemberPolicy": typeof lib_companyMemberPolicy;
  "lib/contextActivation": typeof lib_contextActivation;
  "lib/contextEvals": typeof lib_contextEvals;
  "lib/contextManifests": typeof lib_contextManifests;
  "lib/contextPackages": typeof lib_contextPackages;
  "lib/contextRegistryGate": typeof lib_contextRegistryGate;
  "lib/continuousResearchEvidence": typeof lib_continuousResearchEvidence;
  "lib/continuousResearchProjection": typeof lib_continuousResearchProjection;
  "lib/currentVerification": typeof lib_currentVerification;
  "lib/deliveryAuthorization": typeof lib_deliveryAuthorization;
  "lib/demoSeedExtensions": typeof lib_demoSeedExtensions;
  "lib/dockerAllocationRecovery": typeof lib_dockerAllocationRecovery;
  "lib/dockerSandboxAdmission": typeof lib_dockerSandboxAdmission;
  "lib/evalControlPlaneSchema": typeof lib_evalControlPlaneSchema;
  "lib/evalFrameworkGate": typeof lib_evalFrameworkGate;
  "lib/evidenceAuthority": typeof lib_evidenceAuthority;
  "lib/executionManifest": typeof lib_executionManifest;
  "lib/executionPolicy": typeof lib_executionPolicy;
  "lib/executionProfile": typeof lib_executionProfile;
  "lib/executionProfileAdmission": typeof lib_executionProfileAdmission;
  "lib/executionRecovery": typeof lib_executionRecovery;
  "lib/executionRouting": typeof lib_executionRouting;
  "lib/factoryActionAuthorization": typeof lib_factoryActionAuthorization;
  "lib/factoryAttempt": typeof lib_factoryAttempt;
  "lib/factoryConfiguration": typeof lib_factoryConfiguration;
  "lib/factoryDispatch": typeof lib_factoryDispatch;
  "lib/factoryHealth": typeof lib_factoryHealth;
  "lib/factoryHumanReview": typeof lib_factoryHumanReview;
  "lib/factoryLearning": typeof lib_factoryLearning;
  "lib/factoryMemory": typeof lib_factoryMemory;
  "lib/factoryMemoryDemoSeed": typeof lib_factoryMemoryDemoSeed;
  "lib/factoryMemoryGate": typeof lib_factoryMemoryGate;
  "lib/factoryMemoryTelemetry": typeof lib_factoryMemoryTelemetry;
  "lib/factoryMemoryValidators": typeof lib_factoryMemoryValidators;
  "lib/factoryModelRoute": typeof lib_factoryModelRoute;
  "lib/factoryOverview": typeof lib_factoryOverview;
  "lib/factoryProjectSeed": typeof lib_factoryProjectSeed;
  "lib/factoryRelease": typeof lib_factoryRelease;
  "lib/factoryReviewReadModel": typeof lib_factoryReviewReadModel;
  "lib/factoryWorkerRuntime": typeof lib_factoryWorkerRuntime;
  "lib/factoryWorkflowContract": typeof lib_factoryWorkflowContract;
  "lib/fileTree": typeof lib_fileTree;
  "lib/flags": typeof lib_flags;
  "lib/genomeHash": typeof lib_genomeHash;
  "lib/getActiveTenant": typeof lib_getActiveTenant;
  "lib/githubAppAuth": typeof lib_githubAppAuth;
  "lib/githubAppReadiness": typeof lib_githubAppReadiness;
  "lib/githubCiIngest": typeof lib_githubCiIngest;
  "lib/githubRepoSkills": typeof lib_githubRepoSkills;
  "lib/governedInferenceAdmission": typeof lib_governedInferenceAdmission;
  "lib/governedMcp": typeof lib_governedMcp;
  "lib/graphEngineering": typeof lib_graphEngineering;
  "lib/harnessCapabilities": typeof lib_harnessCapabilities;
  "lib/harnessPrChecks": typeof lib_harnessPrChecks;
  "lib/knowledgeGraph": typeof lib_knowledgeGraph;
  "lib/legacyToolPolicy": typeof lib_legacyToolPolicy;
  "lib/localCandidateRecovery": typeof lib_localCandidateRecovery;
  "lib/loopEngineering": typeof lib_loopEngineering;
  "lib/loopResearchEvidence": typeof lib_loopResearchEvidence;
  "lib/loopWorkflowProjection": typeof lib_loopWorkflowProjection;
  "lib/mergeGates": typeof lib_mergeGates;
  "lib/metaLoopSignals": typeof lib_metaLoopSignals;
  "lib/missionDraft": typeof lib_missionDraft;
  "lib/missionExecution": typeof lib_missionExecution;
  "lib/missionGovernance": typeof lib_missionGovernance;
  "lib/missionIntentContributionValidators": typeof lib_missionIntentContributionValidators;
  "lib/missionIntentContributions": typeof lib_missionIntentContributions;
  "lib/missionPlan": typeof lib_missionPlan;
  "lib/missionPlanningRunState": typeof lib_missionPlanningRunState;
  "lib/missionPromptScheduling": typeof lib_missionPromptScheduling;
  "lib/missionSpec": typeof lib_missionSpec;
  "lib/missionSpecDemo": typeof lib_missionSpecDemo;
  "lib/missionSpecValidators": typeof lib_missionSpecValidators;
  "lib/missionWorkOrderContract": typeof lib_missionWorkOrderContract;
  "lib/modelCatalogScope": typeof lib_modelCatalogScope;
  "lib/modelRouteAdmission": typeof lib_modelRouteAdmission;
  "lib/modelRouting": typeof lib_modelRouting;
  "lib/observability": typeof lib_observability;
  "lib/observabilityPersistence": typeof lib_observabilityPersistence;
  "lib/operatorControls": typeof lib_operatorControls;
  "lib/operatorEvals": typeof lib_operatorEvals;
  "lib/outputValidation": typeof lib_outputValidation;
  "lib/piBridgeEnvelope": typeof lib_piBridgeEnvelope;
  "lib/pilotLiabilityAllocation": typeof lib_pilotLiabilityAllocation;
  "lib/policyV2Verification": typeof lib_policyV2Verification;
  "lib/prEvaluation": typeof lib_prEvaluation;
  "lib/prdParser": typeof lib_prdParser;
  "lib/preExecutionRecovery": typeof lib_preExecutionRecovery;
  "lib/providerLiability": typeof lib_providerLiability;
  "lib/providerLiabilityValidators": typeof lib_providerLiabilityValidators;
  "lib/qualityContract": typeof lib_qualityContract;
  "lib/qualityGateDecision": typeof lib_qualityGateDecision;
  "lib/rateLimit": typeof lib_rateLimit;
  "lib/readOnlyRunControl": typeof lib_readOnlyRunControl;
  "lib/repetitiveTaskCandidates": typeof lib_repetitiveTaskCandidates;
  "lib/repetitiveTasks": typeof lib_repetitiveTasks;
  "lib/repositoryExecutionPolicy": typeof lib_repositoryExecutionPolicy;
  "lib/researchEvidenceBundle": typeof lib_researchEvidenceBundle;
  "lib/researchIngestionPolicy": typeof lib_researchIngestionPolicy;
  "lib/researchSourcePolicy": typeof lib_researchSourcePolicy;
  "lib/reviewIntelligence": typeof lib_reviewIntelligence;
  "lib/reviewIntelligenceValidators": typeof lib_reviewIntelligenceValidators;
  "lib/reviewPackage": typeof lib_reviewPackage;
  "lib/riskClassifier": typeof lib_riskClassifier;
  "lib/runInspector": typeof lib_runInspector;
  "lib/runtimeContract": typeof lib_runtimeContract;
  "lib/sandboxProfileAdmission": typeof lib_sandboxProfileAdmission;
  "lib/sanitize": typeof lib_sanitize;
  "lib/serviceCommandAuth": typeof lib_serviceCommandAuth;
  "lib/skillAutomation": typeof lib_skillAutomation;
  "lib/softwareFactoryControlPlane": typeof lib_softwareFactoryControlPlane;
  "lib/stateMachine": typeof lib_stateMachine;
  "lib/taskAttemptScheduler": typeof lib_taskAttemptScheduler;
  "lib/taskAuthority": typeof lib_taskAuthority;
  "lib/taskEvents": typeof lib_taskEvents;
  "lib/taskProjection": typeof lib_taskProjection;
  "lib/taskWorkflowState": typeof lib_taskWorkflowState;
  "lib/verificationPersistence": typeof lib_verificationPersistence;
  "lib/workOrderCompat": typeof lib_workOrderCompat;
  "lib/workOrderCreate": typeof lib_workOrderCreate;
  "lib/workOrderDispatch": typeof lib_workOrderDispatch;
  "lib/workOrderGovernance": typeof lib_workOrderGovernance;
  "lib/workOrderParentSync": typeof lib_workOrderParentSync;
  "lib/workOrderReadiness": typeof lib_workOrderReadiness;
  "lib/workOrderRevision": typeof lib_workOrderRevision;
  "lib/workOrderSpecification": typeof lib_workOrderSpecification;
  "lib/workOrderSpecificationValidators": typeof lib_workOrderSpecificationValidators;
  "lib/workOrders": typeof lib_workOrders;
  "lib/workflowExecutionControl": typeof lib_workflowExecutionControl;
  "lib/workflowObservability": typeof lib_workflowObservability;
  "lib/workflowRunState": typeof lib_workflowRunState;
  "lib/workflowSnapshot": typeof lib_workflowSnapshot;
  "lib/workflowTaskGuards": typeof lib_workflowTaskGuards;
  "lib/workspaceBindings": typeof lib_workspaceBindings;
  "lib/workspaceRepositories": typeof lib_workspaceRepositories;
  loopEngineering: typeof loopEngineering;
  loops: typeof loops;
  meetings: typeof meetings;
  memoryLifecycle: typeof memoryLifecycle;
  messages: typeof messages;
  metrics: typeof metrics;
  "migrations/backfillInstanceRefs": typeof migrations_backfillInstanceRefs;
  mission: typeof mission;
  missionChat: typeof missionChat;
  missionIntentContributions: typeof missionIntentContributions;
  missionPlanning: typeof missionPlanning;
  missionSpecs: typeof missionSpecs;
  missions: typeof missions;
  modelCatalog: typeof modelCatalog;
  modelRoutingDecisions: typeof modelRoutingDecisions;
  modelRoutingPolicies: typeof modelRoutingPolicies;
  monitoring: typeof monitoring;
  notifications: typeof notifications;
  observability: typeof observability;
  openclawDiscovery: typeof openclawDiscovery;
  "operations/opEvents": typeof operations_opEvents;
  operatorControls: typeof operatorControls;
  operatorEvals: typeof operatorEvals;
  orgAssignments: typeof orgAssignments;
  orgMembers: typeof orgMembers;
  phaseZeroCanary: typeof phaseZeroCanary;
  planning: typeof planning;
  policy: typeof policy;
  prd: typeof prd;
  projects: typeof projects;
  qcArtifacts: typeof qcArtifacts;
  qcFindings: typeof qcFindings;
  qcMetrics: typeof qcMetrics;
  qcRulesets: typeof qcRulesets;
  qcRuns: typeof qcRuns;
  quotaTracking: typeof quotaTracking;
  "registry/agentIdentities": typeof registry_agentIdentities;
  "registry/agentInstances": typeof registry_agentInstances;
  "registry/agentTemplates": typeof registry_agentTemplates;
  "registry/agentVersions": typeof registry_agentVersions;
  "registry/environments": typeof registry_environments;
  "registry/operators": typeof registry_operators;
  "registry/tenants": typeof registry_tenants;
  reports: typeof reports;
  researchIngestion: typeof researchIngestion;
  researchIngestionActions: typeof researchIngestionActions;
  researchSources: typeof researchSources;
  revenue: typeof revenue;
  reviewIntelligence: typeof reviewIntelligence;
  reviews: typeof reviews;
  runs: typeof runs;
  runtimeCompatibility: typeof runtimeCompatibility;
  savedViews: typeof savedViews;
  scheduledJobs: typeof scheduledJobs;
  search: typeof search;
  seed: typeof seed;
  seedAgentHiring: typeof seedAgentHiring;
  seedMemory: typeof seedMemory;
  seedMissionControlDemo: typeof seedMissionControlDemo;
  seedOrgChart: typeof seedOrgChart;
  seedSellerFi: typeof seedSellerFi;
  serviceCommands: typeof serviceCommands;
  sessionBootstrap: typeof sessionBootstrap;
  setupProjects: typeof setupProjects;
  setupSellerFiAgents: typeof setupSellerFiAgents;
  skillAutomations: typeof skillAutomations;
  softwareFactoryControlPlane: typeof softwareFactoryControlPlane;
  squad: typeof squad;
  standup: typeof standup;
  subscriptions: typeof subscriptions;
  taskRelations: typeof taskRelations;
  taskRouter: typeof taskRouter;
  tasks: typeof tasks;
  telegram: typeof telegram;
  telegraph: typeof telegraph;
  testGeneration: typeof testGeneration;
  testRecordings: typeof testRecordings;
  threadManager: typeof threadManager;
  transitions: typeof transitions;
  voice: typeof voice;
  watchSubscriptions: typeof watchSubscriptions;
  webhooks: typeof webhooks;
  workOrders: typeof workOrders;
  workflowMetrics: typeof workflowMetrics;
  workflowRecoveryCanary: typeof workflowRecoveryCanary;
  workflowRuns: typeof workflowRuns;
  workflows: typeof workflows;
  workspaceHostBindings: typeof workspaceHostBindings;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
