import { v } from "convex/values";
export const providerPriceValidator = v.object({
  schema: v.literal("factory-provider-price/v1"),
  provider: v.string(),
  model: v.string(),
  api: v.union(v.literal("RESPONSES"), v.literal("CONVERSE"), v.literal("INVOKE_MODEL")),
  currency: v.literal("USD"),
  effectiveAt: v.number(),
  expiresAt: v.number(),
  source: v.string(),
  evidenceDigest: v.string(),
  inputNanoUsdPerToken: v.number(),
  outputNanoUsdPerToken: v.number(),
  maximumInputTokens: v.number(),
  maximumOutputTokens: v.number(),
  maximumPayloadBytes: v.number(),
  inputBound: v.union(
    v.literal("EXACTLY_ENFORCEABLE"),
    v.literal("CONSERVATIVELY_BOUNDED"),
  ),
  outputIncludesReasoning: v.literal(true),
  inclusiveCacheWorstCase: v.literal(true),
  otherBillableDimensions: v.literal("NONE"),
});
export const providerUsageValidator = v.object({
  requestId: v.string(),
  requestDigest: v.string(),
  provider: v.string(),
  model: v.string(),
  providerRequestId: v.string(),
  usageId: v.string(),
  inputTokens: v.number(),
  outputTokens: v.number(),
  classification: v.union(v.literal("ACTUAL"), v.literal("UNKNOWN")),
  expectedReceiptRevision: v.number(),
});
export const providerScopeValidator = v.object({
  projectId: v.string(),
  repositoryId: v.string(),
  workOrderId: v.string(),
  workOrderRevision: v.number(),
  executionProfileId: v.string(),
  executionProfileDigest: v.string(),
  modelRouteDigest: v.string(),
  priceDigest: v.string(),
});
export const providerHoldValidator = v.object({
  requestId: v.string(),
  requestDigest: v.string(),
  attemptId: v.string(),
  leaseId: v.string(),
  generation: v.number(),
  maximumNanoUsd: v.number(),
  inputTokens: v.optional(v.number()),
  maximumOutputTokens: v.number(),
  state: v.union(
    v.literal("RESERVED"),
    v.literal("UNKNOWN"),
    v.literal("SETTLED"),
    v.literal("OVERRUN"),
  ),
  receiptRevision: v.number(),
  providerRequestId: v.optional(v.string()),
  usageId: v.optional(v.string()),
  accountedNanoUsd: v.optional(v.number()),
  classification: v.union(v.literal("UNKNOWN"), v.literal("ACTUAL")),
  costClassification: v.union(v.literal("UNKNOWN"), v.literal("ESTIMATED")),
  usageDigest: v.optional(v.string()),
});
export const providerReservationValidator = v.object({
  schema: v.literal("factory-provider-reservation/v1"),
  scope: providerScopeValidator,
  maximumNanoUsd: v.number(),
  expiresAt: v.number(),
  maximumRequests: v.number(),
  frozen: v.boolean(),
  holds: v.array(providerHoldValidator),
});
